export const STORAGE_KEY = "petcore.e2e.v1";

export const seedData = {
  labs: [
    {
      id: "lab-patol",
      name: "Lab. Patologia",
      short: "PATOL",
      coordinator: "Dra. Fernanda Lima",
      local: "Bloco B, Sala 203",
      desc: "Histopatologia e citopatologia",
      stock: 87,
      status: "active",
      color: "#285A43",
    },
    {
      id: "lab-imag",
      name: "Diagnóstico por Imagem",
      short: "IMAGEM",
      coordinator: "Dr. Carlos Mendes",
      local: "Bloco C, Sala 101",
      desc: "Raio-X, ultrassom e tomografia",
      stock: 92,
      status: "active",
      color: "#0B7A75",
    },
    {
      id: "lab-aclin",
      name: "Análises Clínicas",
      short: "A.CLIN",
      coordinator: "Dra. Marcia Sousa",
      local: "Bloco B, Sala 108",
      desc: "Hematologia, bioquímica e urinálise",
      stock: 54,
      status: "busy",
      color: "#7B5E20",
    },
    {
      id: "lab-micro",
      name: "Microbiologia",
      short: "MICRO",
      coordinator: "Dr. Rafael Nunes",
      local: "Bloco A, Sala 305",
      desc: "Culturas bacterianas e micológicas",
      stock: 78,
      status: "idle",
      color: "#4E6C8A",
    },
    {
      id: "lab-paras",
      name: "Parasitologia",
      short: "PARAS",
      coordinator: "Dra. Ana Beatriz",
      local: "Bloco A, Sala 210",
      desc: "Endo e ectoparasitas",
      stock: 65,
      status: "active",
      color: "#9A4D2E",
    },
  ],
  tutors: [
    {
      id: "tut-joao",
      name: "João Silva",
      document: "123.456.789-10",
      phone: "(98) 98765-4321",
      email: "joao@email.com",
      city: "São Luís",
      address: "Renascença, São Luís - MA",
    },
    {
      id: "tut-maria",
      name: "Maria Costa",
      document: "234.567.890-11",
      phone: "(98) 99876-5432",
      email: "maria@email.com",
      city: "São Luís",
      address: "Cohama, São Luís - MA",
    },
    {
      id: "tut-pedro",
      name: "Pedro Santos",
      document: "345.678.901-22",
      phone: "(98) 98821-3344",
      email: "pedro@email.com",
      city: "Paço do Lumiar",
      address: "Maiobão, Paço do Lumiar - MA",
    },
    {
      id: "tut-ana",
      name: "Ana Lima",
      document: "456.789.012-33",
      phone: "(98) 97732-9988",
      email: "ana@email.com",
      city: "São José de Ribamar",
      address: "Araçagy, São José de Ribamar - MA",
    },
    {
      id: "tut-carlos",
      name: "Carlos Rocha",
      document: "567.890.123-44",
      phone: "(98) 96643-7766",
      email: "carlos@email.com",
      city: "São Luís",
      address: "Calhau, São Luís - MA",
    },
    {
      id: "tut-fernanda",
      name: "Fernanda M.",
      document: "678.901.234-55",
      phone: "(98) 95521-8877",
      email: "fern@email.com",
      city: "São Luís",
      address: "Turu, São Luís - MA",
    },
  ],
  patients: [
    {
      id: "ani-thor",
      name: "Thor",
      species: "Canino",
      breed: "Golden Retriever",
      weight: "28 kg",
      age: "4 anos",
      tutorId: "tut-joao",
      labs: ["lab-patol", "lab-aclin", "lab-imag"],
      status: "in_service",
      notes: "Histórico de dermatite recorrente.",
      attachments: [
        {
          id: "file-thor-dermato",
          name: "thor-dermatite-inicial.jpg",
          type: "image/jpeg",
          size: 382400,
          uploadedAt: "2026-04-14T10:20:00.000Z",
          dataUrl: "",
        },
      ],
    },
    {
      id: "ani-luna",
      name: "Luna",
      species: "Felino",
      breed: "Siamês",
      weight: "4,2 kg",
      age: "2 anos",
      tutorId: "tut-maria",
      labs: ["lab-micro"],
      status: "waiting",
      notes: "Aguardando coleta para cultura.",
      attachments: [],
    },
    {
      id: "ani-rex",
      name: "Rex",
      species: "Canino",
      breed: "Pastor Alemão",
      weight: "35 kg",
      age: "6 anos",
      tutorId: "tut-pedro",
      labs: ["lab-aclin", "lab-patol"],
      status: "done",
      notes: "Retorno em 30 dias.",
      attachments: [],
    },
    {
      id: "ani-mimi",
      name: "Mimi",
      species: "Felino",
      breed: "Persa",
      weight: "3,8 kg",
      age: "8 anos",
      tutorId: "tut-ana",
      labs: ["lab-patol", "lab-imag"],
      status: "waiting",
      notes: "Paciente sensível a contenção prolongada.",
      attachments: [
        {
          id: "file-mimi-lesao",
          name: "mimi-lesao-cutanea.png",
          type: "image/png",
          size: 291120,
          uploadedAt: "2026-04-15T12:15:00.000Z",
          dataUrl: "",
        },
      ],
    },
    {
      id: "ani-bolt",
      name: "Bolt",
      species: "Canino",
      breed: "Beagle",
      weight: "12 kg",
      age: "1 ano",
      tutorId: "tut-carlos",
      labs: ["lab-paras"],
      status: "in_service",
      notes: "Suspeita de verminose.",
      attachments: [],
    },
    {
      id: "ani-nala",
      name: "Nala",
      species: "Canino",
      breed: "Labrador",
      weight: "24 kg",
      age: "3 anos",
      tutorId: "tut-fernanda",
      labs: ["lab-aclin"],
      status: "done",
      notes: "Exames de rotina concluídos.",
      attachments: [],
    },
  ],
  exams: [
    {
      id: "exa-hemograma-thor",
      patientId: "ani-thor",
      labId: "lab-aclin",
      type: "Hemograma Completo",
      requestedBy: "Dra. Marcia Sousa",
      status: "signed",
      priority: "normal",
      collectedAt: "2026-04-14",
      result: "Anemia leve, hematócrito em 28%.",
      attachments: [
        {
          id: "file-hemograma-thor",
          name: "hemograma-thor.pdf",
          type: "application/pdf",
          size: 186240,
          uploadedAt: "2026-04-14T14:40:00.000Z",
          dataUrl: "",
        },
      ],
    },
    {
      id: "exa-raiox-rex",
      patientId: "ani-rex",
      labId: "lab-imag",
      type: "Raio-X Torácico",
      requestedBy: "Dr. Carlos Mendes",
      status: "ready",
      priority: "normal",
      collectedAt: "2026-04-13",
      result: "Sem alterações cardiopulmonares evidentes.",
      attachments: [
        {
          id: "file-raiox-rex",
          name: "raiox-rex-lateral.jpg",
          type: "image/jpeg",
          size: 725680,
          uploadedAt: "2026-04-13T16:30:00.000Z",
          dataUrl: "",
        },
      ],
    },
    {
      id: "exa-biopsia-mimi",
      patientId: "ani-mimi",
      labId: "lab-patol",
      type: "Biópsia de Pele",
      requestedBy: "Dra. Fernanda Lima",
      status: "processing",
      priority: "high",
      collectedAt: "2026-04-15",
      result: "Amostra em processamento.",
      attachments: [],
    },
    {
      id: "exa-paras-bolt",
      patientId: "ani-bolt",
      labId: "lab-paras",
      type: "Coproparasitológico",
      requestedBy: "Dra. Ana Beatriz",
      status: "requested",
      priority: "normal",
      collectedAt: "2026-04-15",
      result: "Coleta pendente.",
      attachments: [],
    },
  ],
  appointments: [
    {
      id: "age-thor",
      date: "2026-04-15",
      time: "08:00",
      patientId: "ani-thor",
      labId: "lab-patol",
      type: "Biópsia de rotina",
      vet: "Dra. Fernanda",
      status: "confirmed",
    },
    {
      id: "age-luna",
      date: "2026-04-15",
      time: "09:30",
      patientId: "ani-luna",
      labId: "lab-aclin",
      type: "Hemograma + bioquímica",
      vet: "Dra. Marcia",
      status: "confirmed",
    },
    {
      id: "age-rex",
      date: "2026-04-16",
      time: "10:30",
      patientId: "ani-rex",
      labId: "lab-imag",
      type: "Raio-X torácico",
      vet: "Dr. Carlos",
      status: "pending",
    },
  ],
  inventory: [
    {
      id: "inv-amox",
      name: "Amoxicilina 500mg",
      category: "Antibiótico",
      labId: "lab-aclin",
      qty: 145,
      min: 50,
      max: 200,
      expiry: "2026-03-15",
      restricted: false,
    },
    {
      id: "inv-tramadol",
      name: "Tramadol 50mg",
      category: "Analgésico",
      labId: "lab-patol",
      qty: 23,
      min: 30,
      max: 120,
      expiry: "2026-11-20",
      restricted: true,
    },
    {
      id: "inv-dexa",
      name: "Dexametasona 4mg/mL",
      category: "Corticoide",
      labId: "lab-aclin",
      qty: 88,
      min: 20,
      max: 150,
      expiry: "2026-08-10",
      restricted: false,
    },
    {
      id: "inv-dipirona",
      name: "Dipirona Sódica 500mg",
      category: "Analgésico",
      labId: "lab-aclin",
      qty: 12,
      min: 40,
      max: 200,
      expiry: "2026-09-05",
      restricted: false,
    },
    {
      id: "inv-fenobarbital",
      name: "Fenobarbital 100mg",
      category: "Anticonvulsivante",
      labId: "lab-micro",
      qty: 67,
      min: 25,
      max: 100,
      expiry: "2027-01-22",
      restricted: true,
    },
  ],
  users: [
    {
      id: "usr-ewaldo-santana",
      name: "Prof. Dr. Ewaldo Santana",
      email: "ewaldo.santana@uema.br",
      role: "Gestor Hub",
      labId: "",
      status: "active",
    },
    {
      id: "usr-fernanda",
      name: "Dra. Fernanda Lima",
      email: "fernanda@uema.br",
      role: "Coordenador",
      labId: "lab-patol",
      status: "active",
    },
    {
      id: "usr-marcia",
      name: "Dra. Marcia Sousa",
      email: "marcia@uema.br",
      role: "Coordenador",
      labId: "lab-aclin",
      status: "active",
    },
    {
      id: "usr-joao",
      name: "João Alves",
      email: "joao.a@uema.br",
      role: "Aluno / Estagiário",
      labId: "lab-patol",
      status: "active",
    },
  ],
  auditEvents: [
    {
      id: "aud-001",
      at: "2026-04-15T08:14:00.000Z",
      action: "Login no sistema",
      entity: "Sessão",
      actor: "Prof. Dr. Ewaldo Santana",
    },
    {
      id: "aud-002",
      at: "2026-04-15T09:42:00.000Z",
      action: "Laudo assinado: Thor",
      entity: "Exames",
      actor: "Dra. Marcia Sousa",
    },
    {
      id: "aud-003",
      at: "2026-04-15T10:31:00.000Z",
      action: "Saída registrada: Tramadol 50mg",
      entity: "Estoque",
      actor: "Dra. Fernanda Lima",
    },
  ],
};

export const statusLabels = {
  active: "Ativo",
  inactive: "Inativo",
  busy: "Ocupado",
  idle: "Livre",
  waiting: "Aguardando",
  in_service: "Em atendimento",
  done: "Concluído",
  requested: "Solicitado",
  processing: "Em análise",
  ready: "Pronto",
  signed: "Assinado",
  confirmed: "Confirmado",
  pending: "Pendente",
  canceled: "Cancelado",
  normal: "Normal",
  high: "Alta",
  urgent: "Urgente",
};

export const moduleLabels = {
  tutors: "Tutores",
  patients: "Pacientes",
  exams: "Exames",
  appointments: "Agenda",
  inventory: "Estoque",
  labs: "Laboratórios",
  users: "Usuários",
};
